config/routes.rb
Rails.application.routes.draw do
  namespace :profile do
    resources :spaces, only: [:index, :destroy, :show, :edit]
  end

  resources :spaces do
    resources :bookings, only: [:create, :index, :show]
    resources :reviews, only: :create
  end
  devise_for :users

  resources :bookings, only: [:destroy]

  namespace :profile do
    resources :bookings, only: [:index, :show]
  end

  root to: 'spaces#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :space
  belongs_to :mate, class_name: 'User'

  after_create  :update_availabilty_space
  after_destroy :update_availabilty_space

  private

  def update_availabilty_space
    space.update!(available: !persisted?)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :space
  validates :content, length: { minimum: 20 }
end

app/models/space.rb
class Space < ApplicationRecord
  mount_uploader :image, PhotoUploader

  belongs_to :owner, class_name: 'User'#, foreign_key: 'owner_id'
  has_many :bookings, dependent: :destroy
  has_many :mates, through: :bookings
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def available?
    bookings.empty?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spaces, foreign_key: :owner_id
  has_many :bookings, foreign_key: :mate_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  # The callback which stores the current location must be added before you authenticate the user
  # as `authenticate_user!` (or whatever your resource is) will halt the filter chain and redirect
  # before the location can be stored.


  private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
    @space = @booking.space
  end

  def create
    if user_signed_in?
      @booking = Booking.new(params_booking)
      @booking.save
      @space = @booking.space
      change_availability
      redirect_to spaces_path
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy if @booking.mate == current_user

    redirect_to profile_bookings_path
  end

  private

  def params_booking
    params.require(:booking).permit(:mate_id, :space_id, :available)
  end

  def change_availability
    if @space.available?
      @space.update_attribute('available', false)
    else
      @space.update_attribute('available', true)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profile/bookings_controller.rb
class Profile::BookingsController < ApplicationController
  def index
    @bookings      = current_user.bookings

  end


  def show
    @booking = Booking.find(params[:id])
  end

end

app/controllers/profile/spaces_controller.rb
class Profile::SpacesController < ApplicationController
  def index
    @spaces = current_user.spaces
    if @spaces.empty?
      redirect_to new_space_path
    end
  end

  def show
    @space = Space.find(params[:id])
  end

  def edit
    @space = Space.find(params[:id])
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    redirect_to profile_spaces_path
  end

  private

  def space_params
    params.require(:space).permit(:title, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @space = Space.find(params[:space_id])
    @review = Review.new(review_params)
    @review.space = @space
    if @review.save
      respond_to do |format|
        format.html { redirect_to space_path(@space) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'space/show' }
        format.js
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_spaces, only: [:show]

  def index
    @spaces = Space.order(created_at: :desc)

    @spaces = Space.where.not(latitude: nil, longitude: nil)

    @markers = @spaces.map do |space|
      {
        lng: space.longitude,
        lat: space.latitude,
        infoWindow: { content: render_to_string(partial: "../views/spaces/popup", locals: { space: space }) }
      }
    end
  end

  def show
    @owner = @space.owner
    @user  = current_user
    @booking = Booking.new(mate: current_user, space: @space)
    @review = Review.new
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.owner = current_user
    if @space.save
      redirect_to profile_spaces_path
    else
      ap @space.errors
      render :new
      @space.save
    end
  end

  def edit
  end

  def update
    @space = Space.find(params[:id])
    @space.update(space_params)
    @space.save
    redirect_to profile_space_path
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    redirect_to profile_spaces_path
  end

  private

  def set_spaces
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div>

  <%= simple_form_for [@space, @booking] do |f| %>
  <%= f.input :mate_id, as: :hidden %>
  <%= f.input :space_id, as: :hidden %>

  <%= f.submit "add a booking", class: "btn btn-warning" %>
<% end %>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@booking] do |f| %>
  <%= f.input :mate_id %>
  <%= f.input :space_id %>

  <%= f.submit "add a booking", class: "btn btn-primary" %>
<% end %>

app/views/bookings/show.html.erb
<div class="container">
  <h1>These are your booking</h1>

  <%= @space.description %>

  <%= link_to "Delete my booking", booking_path(@booking),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sharlie</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

  <body class="<%= body_class %>">
    <%= render "shared/navbar" %>
    <%= yield :extra_banner %>
    <%= yield :extra_header %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for([ space, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit, class: "btn btn-danger" %>
<% end %>

app/views/reviews/_show.html.erb
<p><strong><%= current_user.first_name %></strong> : <%= review.content %></p>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", space: @space, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", space: @space, review: Review.new %>');
<% end %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url('<%= @space.image %>');">
</div>

app/views/shared/_banner_landing.html.erb
<% if user_signed_in? %>
<% else %>
<div class="banner-landing" style="background-image: url('http://res.cloudinary.com/hrscywv4p/image/upload/c_limit,fl_lossy,h_1500,w_2000,f_auto,q_auto/v1/1441878/saloon_HD_rv7ekk.jpg');">

  <div class="banner-content">
    <div class="typed">
      <h1 id="banner-landing"></h1>
    </div>


      <%= simple_form_for(User.new, url: user_registration_path) do |f| %>
      <div class="sign">
        <div>
          <%= f.input :email,
                      required: true,
                      autofocus: true ,
                      input_html: { autocomplete: "email" }%>
        </div>
        <div>
          <%= f.input :password,
                      required: true,
                      hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                      input_html: { autocomplete: "new-password" } %>
          </div>
          <div>
          <%= f.input :password_confirmation,
                      required: true,
                      input_html: { autocomplete: "new-password" } %>
        </div>

        <div class="form-actions text-center">
          <%= f.button :submit, "Je m'inscris", class:"btn btn-warning btn-lg"%>
        </div>
        </div>
      <% end %>

  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>

    <div class="navbar-wagon">
      <!-- Logo -->
      <a href="/" class="navbar-wagon-brand">
        <%= image_tag "logo_B.png", alt: "logo" %>
      </a>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">

        <%= link_to "Mes Co'works", profile_spaces_path, class:"links_navbar" %>
        <%= link_to "Mes Réservations", profile_bookings_path, class:"links_navbar" %>

        <!-- Profile picture with dropdown list -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag current_user.image, alt: "alttext", class:'avatar dropdown-toggle', id:"navbar-wagon-menu", data: { toggle: 'dropdown' } %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Dropdown appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">My Space</a></li>
            <li><a href="#">My Booking</a></li>
          </ul>
        </div>
      </div>
    </div>


  <% else %>

  <div class="navbar-wagon">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "logo_B.png", alt: "logo" %>
    </a>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <%= link_to "Connexion", new_user_session_path, class: "btn btn-large btn-nav btn-info" %>
     </div>
    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">à propos</a></li>
          <li><%= link_to "M'inscrire", new_user_registration_path %></li>
          <li><%= link_to "Connexion", new_user_session_path, class: "btn btn-lg btn-info" %></li>
        </ul>
      </div>
    </div>
  </div>

  <% end %>

app/views/spaces/_form.html.erb
<%= simple_form_for(@space) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.label :image %>
    <%= f.file_field :image %>

  </div>

    <div class="form-actions">
  <%= link_to profile_spaces_path(@space) do %>
      <%= f.button :submit, 'Créer un Co\'Work' %>
  <% end %>
    </div>
<% end %>

app/views/spaces/_popup.html.erb
<ul style="list-style-type: none">
  <li><strong>Prix : </strong><%= space.price %> €/jour</li>
  <li><strong>Nom du lieu : </strong><%= space.title %></li>
  <li><strong>Description : </strong><%= h truncate(space.description, :length => 80) %></li>
</ul>

<div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= space.image %>');">
</div>

app/views/spaces/destroy.html.erb
<h1>Spaces#detroy</h1>
<p>Find me in app/views/spaces/detroy.html.erb</p>

app/views/spaces/detroy.html.erb
<h1>Spaces#detroy</h1>
<p>Find me in app/views/spaces/detroy.html.erb</p>

app/views/spaces/edit.html.erb
<h1>Spaces#edit</h1>
<p>Find me in app/views/spaces/edit.html.erb</p>

app/views/spaces/index.html.erb
<% content_for :extra_banner do %>
  <%= render "shared/banner_landing" %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="main-container">
      <div class="col-xs-12 col-md-8">

        <h1 class="padding-left">Tous les Co'Works</h1>
        <%  @spaces.each do |space| %>
          <%= link_to space_path(space) do %>

          <div class="col-xs-12 col-sm-4 card_margin">

            <div class="card-space">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= space.image %>');">
                <% if space.available? %>
                <div class="space-available"><i class="fas fa-dot-circle"></i></div>
                <% else %>
                <div class="space-not-available"><i class="fas fa-dot-circle"></i></div>
                <% end %>
                <div class="price"> <%= space.price %> €</div>
                <div class="card-description">
                  <h2><%= space.title %></h2>
                </div>
              </div>
              <div class="foot_card">

                <div class="card-rating">
                   <div class="jaune">
                       <% space.ranking.times do %>
                         <%= link_to icon('fa', 'star'), "#", style:"color: #F9C72E;" %>
                       <% end %>
                     </div>
                     <div class="grey">
                       <% (5-space.ranking).times do %>
                         <%= link_to icon('fa', 'star'), "#", style:"color: #CCCCCC;" %>
                       <% end %>
                    </div>

                </div>
                <div class="name_user_card">Chez <%= space.owner.first_name %></div>
                <%= image_tag space.owner.image, alt: "user_img", class: "card-user" %>

              </div>
            </div>

          </div>

          <% end %>
        <% end %>
      </div>



      <div class="col-xs-12 col-md-4">
        <div
        id="map"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>

  </div>
</div>

app/views/spaces/new.html.erb
<div class="container">

  <h1>Create a Space</h1>

  <%= render 'form', space: @space %>
  <%= link_to 'Back', spaces_path %>

</div>

app/views/spaces/show.html.erb
<div class="container">
  <% content_for :extra_header do %>
    <%= render "shared/banner" %>
  <% end %>

  <div class="row">

    <div class="col-xs-12 col-sm-8">
      <h1><%= @space.title %></h1>

      <div class="show-rating">
        <div class="card-rating">
           <div class="jaune">
               <% @space.ranking.times do %>
                 <%= link_to icon('fa', 'star'), "#", style:"color: #F9C72E;" %>
               <% end %>
             </div>
             <div class="grey">
               <% (5-@space.ranking).times do %>
                 <%= link_to icon('fa', 'star'), "#", style:"color: #CCCCCC;" %>
               <% end %>
            </div>
        </div>
      </div>

      <div class="image">
        <div><%= image_tag @space.owner.image, alt: "user_img", class: "card-user-show" %></div>
        <p class="owner-name"><%= @owner.first_name %> <%= @owner.last_name %></p>
      </div>
      <div class="description">
        <p class="renseignement">Renseignement sur votre hôte :</p>
        <p class="describe">Description : <%= @space.description %></p>
        <p class="owner">Email : <%= @owner.email %></p>
      </div>

      <div class="owner_description">
        <div class="description">
          <p class="renseignement">Renseignement sur votre hôte :</p>
          <p>Bienvenue dans notre "creuset lyonnais". A l'origine, un creuset est un pot en métal servant à la fusion d'autres métaux
          De nos jours, il évoque dans des expressions imagées, des lieux où ont été brassés différents groupes de personnes.</p>
        </div>
      </div>

      <div class="owner_description">
        <h2 class="renseignement">Équipement :</h2>
        <div class="flex_box_equipement">
          <div>
            <p><i class="fas fa-snowflake"></i> Climatisation</p>
            <p><i class="fas fa-wifi"></i> Wi-Fi</p>
          </div>
          <div>
            <p><i class="fas fa-sun"></i> Chauffage</p>
            <p><i class="fas fa-bath"></i> Équipements de base</p>
          </div>
        </div>
      </div>

      <div class="wrapper-reviews">
        <h2>
          <%= pluralize @space.reviews.size, "review" %>
        </h2>

        <div id="reviews">
          <% if @space.reviews.blank? %>
            Soit le primier à laisser un commantaire à <strong><%= @owner.first_name %></strong>
          <% else %>
            <% @space.reviews.each do |review| %>
              <%= render 'reviews/show', review: review %>
            <% end %>
          <% end %>
        </div>
          <%= render 'reviews/form', space: @space, review: @review %>
      </div>
    </div>

    <div class="col-xs-12 col-md-4 book-card-col">
      <div class="book-card">
        <% if @space.available? %>
          <p class="text-center"> L'appartement est disponible</p>
          <%= render 'bookings/form' %>
        <% else %>
          <p class="text-center">Cet appartement n'est plus disponible</p>
          <%= link_to "Retour aux espaces", spaces_path, class: "btn btn-large btn-nav btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/spaces/update.html.erb
<h1>Spaces#update</h1>
<p>Find me in app/views/spaces/update.html.erb</p>